{
 "title": "Analytics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Среднее количество минут пользовательской сессии",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    date as time,\n    avg_duration_minutes\nFROM session_metrics_daily\nWHERE date >= toDate(now() - interval 30 day)\nORDER BY date"
    }
   ]
  },
  {
   "title": "Медианное количество минут пользовательской сессии",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    date as time,\n    median_duration_minutes\nFROM session_metrics_daily\nWHERE date >= toDate(now() - interval 30 day)\nORDER BY date"
    }
   ]
  },
  {
   "title": "Топ-10 посещаемых страниц",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 16, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nSUM(view_count) as total_views,\n    url\nFROM top_pages_daily\nWHERE date >= toDate(now() - interval 7 day)\n    AND rank <= 10\nGROUP BY url\nORDER BY total_views DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Количество пользовательских сессий",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    date as time,\n    session_count\nFROM session_metrics_daily\nWHERE date >= toDate(now() - interval 30 day)\nORDER BY date"
    }
   ]
  },
  {
   "title": "WAU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    date as time,\n    wau as WAU\nFROM user_activity_daily\nWHERE date >= toDate(now() - interval 30 day)\nORDER BY date"
    }
   ]
  },
  {
   "title": "DAU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    date as time,\n    dau\nFROM user_activity_daily\nWHERE date >= toDate(now() - interval 30 day)\nORDER BY date"
    }
   ]
  },
  {
   "title": "MAU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    date as time,\n    mau as MAU\nFROM user_activity_daily\nWHERE date >= toDate(now() - interval 30 day)\nORDER BY date"
    }
   ]
  },
  { "title": "Распределение устройств", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "По количеству уникальных пользователей",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    device_type,\n    SUM(unique_users) as total_users\nFROM device_distribution_daily\nWHERE date = today()\nGROUP BY device_type\nORDER BY total_users DESC"
    }
   ]
  },
  {
   "title": "По количеству событий",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    device_type,\n    SUM(device_events) as total_events\nFROM device_distribution_daily\nWHERE date = today()\nGROUP BY device_type\nORDER BY total_events DESC"
    }
   ]
  },
  {
   "title": "Соотношение клика к просмотру",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (SUM(clicks) / SUM(views)) as conversion_rate\nFROM element_conversion\nWHERE date >= toDate(now() - interval 7 day)\n    AND views > 0\nORDER BY conversion_rate DESC\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Соотношение конверсии клика к просмотру",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    element_id,\n    (SUM(clicks) / SUM(views)) as conversion_rate\nFROM element_conversion\nWHERE date >= toDate(now() - interval 7 day)\n    AND views > 0\nGROUP BY element_id\nORDER BY conversion_rate DESC\nLIMIT 20"
    }
   ]
  }
 ]
}